# Generated by Django 6.0.4 on 2026-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ناوی یەکەم')),
                ('last_name', models.CharField(max_length=100, verbose_name='ناوی کۆتایی')),
                ('date_of_birth', models.DateField(verbose_name='بەرواری لەدایکبوون')),
                ('gender', models.CharField(choices=[('M', 'نێر'), ('F', 'مێ'), ('O', 'تر')], max_length=1, verbose_name='ڕەگەز')),
                ('phone', models.CharField(max_length=20, verbose_name='ژمارەی تەلەفۆن')),
                ('address', models.TextField(blank=True, verbose_name='ناونیشان')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='گرووپی خوێن')),
                ('allergies', models.TextField(blank=True, verbose_name='هەستیاری')),
                ('medical_history', models.TextField(blank=True, verbose_name='مێژووی نەخۆشی')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='ناوی پەیوەندیکاری بەپەلە')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='تەلەفۆنی بەپەلە')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نەخۆش',
                'verbose_name_plural': 'نەخۆشەکان',
                'ordering': ['-created_at'],
            },
        ),
    ]
