# Generated by Django 6.0.4 on 2026-04-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='بەروار')),
                ('time', models.TimeField(verbose_name='کاتژمێر')),
                ('status', models.CharField(choices=[('waiting', 'چاوەڕوان'), ('active', 'چالاک'), ('done', 'تەواو'), ('cancelled', 'هەڵوەشاوە')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='تێبینی')),
                ('diagnosis', models.TextField(blank=True, verbose_name='دیاریکردنی نەخۆشی')),
                ('prescription', models.TextField(blank=True, verbose_name='دەرمان')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='کرێ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پارەدراوە')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'نوێنەری کات',
                'verbose_name_plural': 'نوێنەرییەکانی کات',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
